### ISSUE TITLE
Can you please add a license?

### ISSUE THREAD

**Issue by olsonjeffery** [0/msp430-rng#1]
Hi,

I'm working on an msp430 project and would like to incorporate this code into it. Can you please include a LICENSE.txt and annotate the source/headers and README file so I (and others who come after) can understand the guidelines you have in mind?

When no license is included, the legal implication is that the author is _extending no license_, that is, it cannot be used by anyone. Was this your intention?

Thanks for the library, in any event.

**Comment by 0** [comment]
Thanks for bringing this up! My intention was to allow use by anyone, but this code predates my habit of putting a license in all my projects.

I think 986fcf9 takes care of this issue. I do not typically put any license information in the individual files (unless their licensing is different from the rest), since my understanding is that a "global" declaration in the README is sufficient as a statement of intent.
